# Generated by Django 3.2.5 on 2021-07-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_barcodescanhit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachebarcode',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
